version: '2'

services:
  app:
    build: .
    volumes:
      - ./public:/usr/src/app/public
      - ./server:/usr/src/app/server
      - ./shared:/usr/src/app/shared
    ports:
      - '80:80'
      - '1234:1234'
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: monopvply
      MYSQL_ROOT_PASSWORD: 123456