version: '2'

services:
  app:
    build: .
    volumes:
      - ./public:/usr/src/app/public
      - ./server:/usr/src/app/server
      - ./shared:/usr/src/app/shared
    ports:
      - '80:80'
      - '1234:1234'